### ISSUE TITLE
Change existing code indentation to 4

### ISSUE THREAD

**Issue by ACG8** [ACG8/kestral-compiler-group-B#11]
We should go back through the code and redefine the tab size to 4. We should also use 4-space tabs going forward.

**Comment by emmahawk** [comment]
It appears that the code indentation is a function of the editors on our personal computers. Change the settings on your computer, and tab size should be easily changed to 4 for personal readability.

Note: some editors may be set to add spaces for tabs, and this may cause problems across computers (though we haven't found any yet). Consider changing?
