### ISSUE TITLE
Figure out difference between string_put and symbol_put

### ISSUE THREAD

**Issue by ACG8** [ACG8/kestral-compiler-group-B#16]
In several cases, /jones/ replaces ```string_put``` with ```symbol_put```. What is the difference between these?

**Comment by emmahawk** [comment]
symbol_put uses string_put in its definition. It is a way of organizing the code in a logical way, especially if changes need to be made later for each functionality (strings vs symbols), e.g., for the code generator putting symbols or strings into files (we discussed this as a group at a meeting). Please add more comments if you find more explanations.
