### ISSUE TITLE
Figure out BNF grammar for parser

### ISSUE THREAD

**Issue by ACG8** [ACG8/kestral-compiler-group-B#34]
We need a BNF grammar along with start and follow symbols so that we know which things to implement. The EBNF grammar specification is here:
http://homepage.divms.uiowa.edu/~jones/compiler/kestrel/kestrelEBNF.txt

**Comment by agiegerich** [comment]
I added the BNF and start-follow sets to the project as text files. You should still go ahead and do it (it doesn't take long) so we can diff and make sure we get the same thing.
