### ISSUE TITLE
Lex_put() needs to be able to print an identifier or keyword

### ISSUE THREAD

**Issue by ACG8** [ACG8/kestral-compiler-group-B#4]

**Comment by ACG8** [comment]
From the language specifications:

> As in most programming languages, an identifier consists of a letter followed by any number of letters or digits
>
> ```<identifier> ::= <letter> { <letter> | <digit> }```
>
> There is no limit on the length of an identifier, and all characters within an identifier are significant. Note that the formal definition given here is ambiguous! Because white space between consecutive lexemes is optional, this definition permits ab to be read as two consecutive identifiers, a followed by b. This ambiguity is resolved informally by what is usually called the greedy rule: Where there is a possible ambiguity, the interpretation packing the most characters into a single chunk is accepted. In this case, we consume the longest possible identifier before declaring that the lexeme has ended. Thus, where consecutive identifiers are intended, they must be separated by non-empty white space.

**Comment by agiegerich** [comment]
I implemented the printing of identifiers while working on the parsing of identifiers. Keywords still need to be done.

**Comment by ACG8** [comment]
This is pretty much done
