### ISSUE TITLE
2 Character Punctuation Marks in Lexical Analyzer

### ISSUE THREAD

**Issue by emmahawk** [ACG8/kestral-compiler-group-B#5]
Does this mean within a string or outside of a string, as part of the makeup of the line of code? We probably need to see the context. Can there be more than two character punctuation marks?

**Comment by agiegerich** [comment]
This may intersect with Issue 1 because the '-' counts as punctuation and the two character punctuation "--" is the beginning of a comment.

**Comment by ACG8** [comment]
By the way, you can reference an issue with a link by putting a '#' before the number, like this:
#1

**Comment by agiegerich** [comment]
That's useful, thanks Ananda!

**Comment by ACG8** [comment]
Found the documentation on punctuation marks:

> The following punctuation marks occuring in Kestrel programs are classified as lexemes:
> ```
> <punctuation> ::= ";"   -- statement terminator/separator
>                |  "="   -- assignment and comparison
>                |  ":"   -- definition
>                |  "("   -- delimiting expression lists
>                |  "["   --     "
>                |  "{"   --     "
>                |  ")"   --     "
>                |  "]"   --     "
>                |  "}"   --     "
>                |  ","   -- separating expressions 
>                |  "@"   -- pointer definition and use
>                |  ".."  -- subrange constructor
>                |  "/="  -- comparison (≠)
>                |  ">"   -- comparison
>                |  ">="  -- comparison (≥)
>                |  "<"   -- comparison
>                |  "<="  -- comparison (≤)
>                |  "+"   -- arithmetic
>                |  "-"   -- arithmetic (unary or binary)
>                |  "*"   -- arithmetic (×)
>                |  "/"   -- arithmetic (÷)
>                |  "%"   -- arithmetic (remainder)
>                |  "&"   -- logic (∧)
>                |  "|"   -- logic (∨)
>                |  "~"   -- logical not or one's complement (¬)
>                |  "."   -- field selection
> ```
> As the language is refined, meanings may be given to additional punctuation marks (notably, exclusive or is missing above).
> 
> Note that several of the punctuation marks above are compound marks made up of several characters. Above the lexical level, these are always seen as single lexemes. Thus, for example, ">=" is a single lexeme quite distinct from "> =". The latter is seen as two lexemes, ">" followed by "=" (a combination with no defined meaning).

The last paragraph explains what two-character punctuation marks are.

**Comment by emmahawk** [comment]
Pretty sure that I fixed it. I hard-coded a check for the next value from this list, and added the two-char punctuation mark to the value.

**Comment by emmahawk** [comment]
I added a review tag, but it seems to work.
