### ISSUE TITLE
Missing Code for End of File Lexeme Types

### ISSUE THREAD

**Issue by emmahawk** [ACG8/kestral-compiler-group-B#6]
What are the different ways to end a file? Can they be used for other things, and if so, how do we tell them apart?

**Comment by junhkang** [comment]
I just ended code with just warning about EoF, should I make something return?

**Comment by ACG8** [comment]
@junhkang I can't find your code in lexical.c; did you commit your changes?

**Comment by emmahawk** [comment]
@junhkang I don't see them either. remember to do a 'svn commit' with a proper message :)

**Comment by ACG8** [comment]
From the documentation:

> At the lexical level, a Kestrel program consists of a sequence of lexemes intermixed with arbitrary amounts of white space and terminated by an end of file:
> ```
> <kestrel program> ::= { { <white space> } <lexeme> }
>                       { <white space> } <end of file>
> ```
> In what follows, however, we will cheat and view the end of file mark as a kind of lexeme, one that occurs only once in any program and only at the end. This allows us to describe a Kestrel program as follows:
> 
> ```<kestrel program> ::= { { <white space> } <lexeme> }```

and

> Lexemes include all of the symbols of the programming language, including the end of file:
> 
> ```
> <lexeme> ::= <identifier>
>           |  <number>
>           |  <string>
>           |  <punctuation>
>           |  <end of file>
> ```

The purpose of lex_put is just to reconstruct the text of the lexeme, though; I don't think it needs to be anything special. Basically, you just need to let the user know that you are at the end of the file. It would be cool if you could also name the file that was just lexed, of course, though probably not necessary.
